package main

import (
	"fmt"
	"os"
)

func write(f *os.File, content string) {
	_, err := f.WriteString(content)
	if err != nil {
		fmt.Println("Error writing to shell script file:", err)
		os.Exit(1)
	}
}

func (cfg *ShellyCfg) shellGen() {
	fmt.Println(prettyprint(cfg))
	fmt.Println("creating user files in src")

	// write main script content
	cfg.commandFunc("root")

	// compile the final script
	var permissions os.FileMode = 0o755
	filename := fmt.Sprintf("./%s", cfg.Name)
	f, err := os.OpenFile(filename, os.O_CREATE|os.O_WRONLY, permissions)
	if err != nil {
		fmt.Println("Error creating shell script file:", err)
		return
	}
	defer f.Close()

	// write shebang
	write(f, cfg.shebang()+"\n\n")

	write(f, "# :command.master_script"+"\n\n")
	write(f, "# :command.version_command\nversion_command() {\n\techo \"$version\"\n}"+"\n\n")

	// usage section
	write(f, "# :command.usage\n"+cfg.Name+"_usage() {}"+"\n\n")
	write(f, "# :command.usage\n"+cfg.Name+"_install_usage() {}"+"\n\n")
	write(f, "# :command.usage\n"+cfg.Name+" for each sub command"+"\n\n")

	// normalize input
	write(f, "# :command.normalize_input"+"\n")
	write(f, "# :command.normalize_input_function"+"\n")
	write(f, "normalize_input() {\n"+"}\n\n")

	// inspect args
	write(f, "# :command.inspect_args"+"\n")
	write(f, "inspect_args() {\n"+"}\n\n")

	// command functions
	write(f, "# :command.command_functions\n\n")
	write(f, "# :# :command.function\n\n")
	write(f, cfg.Name+"_install_gup_command() {\n# src/command_command.sh\n# input from cmd_command.sh\n}\n\n")

	// command parse_requirements
	write(f, "# :command.parse_requirements"+"\n")
	write(f, "parse_requirements() {\n"+"}\n\n")

	write(f, "# :command.parse_requirements"+"\n")
	write(f, cfg.Name+"_install_parse_requirements() {\n"+"}\n\n")

	// :command.initialize
	write(f, "# :command.initialize\n"+"initialize() {\n\tversion="+cfg.Version+"\n\tset -e\n}\n\n")

	// :command.run
	write(f, "# :command.run\n"+"run() {\n}\n\n")

	// :command.start
	write(f, "# :command.start\n")
	write(f, "case \"$0\" in\n")
	write(f, "\t*/*) script_name=${0##*/} ;;\n")
	write(f, "\t*)   script_name=$0 ;;\n")
	write(f, "esac"+"\n\n")
	write(f, "if [ \"$script_name\" = \"$(basename \"$0\")\" ]; then\n")
	write(f, "\t# :command.start\n")
	write(f, "\tcommand_line_args=\"$@\"\n")
	write(f, "\tinitialize\n")
	write(f, "\trun \"$@\"\n")
	write(f, "fi\n")

	fmt.Printf("created ./%s.sh\n", cfg.Name)

	// final message
	fmt.Printf("run ./%s --help to test your bash script\n", cfg.Name)
}

func (cfg *ShellyCfg) shebang() string {
	return "#!/usr/bin/env sh\n# This script was generated by shelly\n# Modifying it manually is not recommended"
}

func (cfg *ShellyCfg) commandFunc(command string) {
	filecontent := fmt.Sprintf("echo \"# This file is located at 'src/%s_command.sh'.\n"+
		"echo \"# It contains the implementation for the '%s' command.\"\n"+
		"echo \"# The code you write here will be wrapped by a function named '%s_command()'.\"\n"+
		"echo \"# Feel free to edit this file; your changes will persist when regenerating.\"\n"+
		"inspect_args\n",
		command, command, command)
	filename := fmt.Sprintf("src/%s_command.sh", command)
	if _, err := os.Stat(filename); os.IsNotExist(err) {
		cfg.writeCommand("src/"+command+"_command.sh", filecontent)
	}
}

func (cfg *ShellyCfg) writeCommand(filename, content string) error {
	f, err := os.Create(fmt.Sprintf("./%s", filename))
	if err != nil {
		fmt.Println("Error creating shell script file:", err)
		return err
	}
	defer f.Close()
	write(f, content)
	return nil
}
